cargo binstall git-delta
cargo binstall cargo-edit
cargo binstall ripgrep
cargo binstall flamegraph
cargo binstall oha
cargo binstall just
cargo binstall hyperfine
cargo binstall tokei
cargo binstall cargo-get
cargo binstall cargo-bump
