cargo install git-delta
cargo install cargo-edit
cargo install ripgrep
cargo install flamegraph
cargo install oha
cargo install just
cargo install hyperfine
cargo install tokei
cargo install cargo-get
cargo install cargo-bump
