name: ci

on:
  push:

jobs:
  buildx:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.config/terminal/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:latest, ${{ github.repository }}:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ github.token }}